package epheluv.agri.demo.rules
import epheluv.agri.demo.SensorData;
import epheluv.agri.demo.AirConditioningSystem;
import epheluv.agri.demo.DehumidificationSystem;
import epheluv.agri.demo.VentilationSystem;

rule "High Temperature Trigger Air Conditioning Cooling"
    when
        $data : SensorData(
            sensorType == "temperature",
            value > 35
        )
    then
        AirConditioningSystem.activateCooling($data);
end

rule "Normal Temperature Stop Air Conditioning"
    when
        $data : SensorData(
            sensorType == "temperature",
            value <= 30
        )
    then
        AirConditioningSystem.deactivateCooling($data);
end

rule "High Humidity Trigger Dehumidification"
    when
        $data : SensorData(
            sensorType == "humidity",
            value > 70
        )
    then
        DehumidificationSystem.activateDehumidification($data);
end

rule "Normal Humidity Stop Dehumidification"
    when
        $data : SensorData(
            sensorType == "humidity",
            value <= 60
        )
    then
        DehumidificationSystem.deactivateDehumidification($data);
end

rule "High CO2 Trigger Ventilation"
    when
        $data : SensorData(
            sensorType == "co2",
            value > 1500
        )
    then
        VentilationSystem.activateVentilation($data);
end

rule "Normal CO2 Stop Ventilation"
    when
        $data : SensorData(
            sensorType == "co2",
            value <= 1000
        )
    then
        VentilationSystem.deactivateVentilation($data);
end

