package epheluv.agri.demo.rules

import epheluv.agri.demo.SensorData

// 温度告警
rule "High Temperature Alert"
    when
        $data: SensorData(sensorType == "temperature", value > 35.0)
    then
        System.out.println("[告警] 温度过高！区域：" + $data.getZoneId() + "，温度：" + $data.getValue() + "℃");
end

// 湿度告警
rule "Abnormal Humidity Alert"
    when
        $data : SensorData(sensorType == "humidity", value < 30 || value > 70)
    then
        System.out.println("湿度异常: 区域 " + $data.getZoneId() + " 湿度值 " + $data.getValue());
end

// 气压告警
rule "Abnormal Pressure Alert"
    when
        $data : SensorData(sensorType == "pressure", value < 975 || value > 1025)
    then
        System.out.println("气压异常: 区域 " + $data.getZoneId() + " 气压值 " + $data.getValue());
end

//二氧化碳告警
rule "Abnormal CO2 Alert"
    when
        $data : SensorData(sensorType == "co2", value > 1500)
    then
        System.out.println("二氧化碳浓度过高: 区域 " + $data.getZoneId() + " 二氧化碳浓度值 " + $data.getValue());
end